### ISSUE TITLE
建议增加 Object.assign 的 polyfill

### ISSUE THREAD

**Issue by ETiV** [diamont1001/jrQrcode#2]
在微信浏览器里无法生成，经查是缺少了 Object.assign (ES6)方法

在赶项目，懒得PR了…

**Comment by diamont1001** [comment]
好咧，感谢，我看看

**Comment by diamont1001** [comment]
commit: 5b8c79d1a62c3bd4935244e20faea3d57488951c

已经解决了，npm包版本：jr-qrcode@1.0.5
