### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by jwteng** [diamont1001/jrQrcode#5]
请问这个library可以用于angular 7(typescript)吗？ 谢谢

**Comment by diamont1001** [comment]
这个库跟任何框架没什么冲突，它只是利用二维码核心算法去生成二维码，然后再利用 canvas 去转换成 base64 图片并输出的过程，所以把它用在哪里都可以。

**Comment by jwteng** [comment]
我已调了二维码的高度及宽度为500px,不过怎么二维码画出来时依然是默认的256px? 谢谢亲

**Comment by diamont1001** [comment]
```js
var imgBase64 = jrQrcode.getQrBase64('text abc', {
  width: 500,
  height: 500
});
```

是这么调用的吗？
